const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('sonos', {
  discover: () => ipcRenderer.invoke('discover'),
  getState: (ip) => ipcRenderer.invoke('get-state', ip),
  play: (ip) => ipcRenderer.invoke('play', ip),
  pause: (ip) => ipcRenderer.invoke('pause', ip),
  next: (ip) => ipcRenderer.invoke('next', ip),
  previous: (ip) => ipcRenderer.invoke('previous', ip),
  setVolume: (ip, vol) => ipcRenderer.invoke('set-volume', ip, vol),
  toggleMute: (ip) => ipcRenderer.invoke('toggle-mute', ip),
  seek: (ip, pos) => ipcRenderer.invoke('seek', ip, pos),
  getQueue: (ip) => ipcRenderer.invoke('get-queue', ip),
  getFavorites: (ip) => ipcRenderer.invoke('get-favorites', ip),
  getPlaylists: (ip) => ipcRenderer.invoke('get-playlists', ip),
  playFavorite: (ip, fav) => ipcRenderer.invoke('play-favorite', ip, fav),
  playPlaylist: (ip, pl) => ipcRenderer.invoke('play-playlist', ip, pl),
  removeFromQueue: (ip, idx) => ipcRenderer.invoke('remove-from-queue', ip, idx),
  reorderTrack: (ip, from, to) => ipcRenderer.invoke('reorder-track', ip, from, to),
  getPlayMode: (ip) => ipcRenderer.invoke('get-play-mode', ip),
  setPlayMode: (ip, mode) => ipcRenderer.invoke('set-play-mode', ip, mode),
  selectTrack: (ip, num) => ipcRenderer.invoke('select-track', ip, num),
  onStateUpdate: (cb) => ipcRenderer.on('state-update', (_, data) => cb(data)),
  watchDevice: (ip) => ipcRenderer.send('watch-device', ip),
  stopWatching: () => ipcRenderer.send('stop-watching'),
  saveLastDevice: (device) => ipcRenderer.send('save-last-device', device),
  onAutoSelectDevice: (cb) => ipcRenderer.on('auto-select-device', (_, data) => cb(data)),
  playPauseMinibar: (action) => ipcRenderer.send('minibar-play-pause', action),
  minibarAction: (action) => ipcRenderer.send('minibar-action', action),
  getLyrics: (title, artist) => ipcRenderer.invoke('get-lyrics', title, artist),
  resizeMinibar: (expanded) => ipcRenderer.send('minibar-resize', expanded),
  getMediaSessions: () => ipcRenderer.invoke('get-media-sessions'),
  setSourceMode: (mode) => ipcRenderer.send('set-source-mode', mode),
  setTheme: (theme) => ipcRenderer.send('set-theme', theme),
  onThemeChanged: (cb) => ipcRenderer.on('theme-changed', (_, theme) => cb(theme)),
  // Sleep timer
  setSleepTimer: (minutes) => ipcRenderer.send('set-sleep-timer', minutes),
  getSleepTimer: () => ipcRenderer.invoke('get-sleep-timer'),
  onSleepTimerDone: (cb) => ipcRenderer.on('sleep-timer-done', () => cb()),
  // Speaker grouping
  getGroups: () => ipcRenderer.invoke('get-groups'),
  joinGroup: (ip, coordIp) => ipcRenderer.invoke('join-group', ip, coordIp),
  leaveGroup: (ip) => ipcRenderer.invoke('leave-group', ip),
  // Auto-switch
  onAutoSwitchLocal: (cb) => ipcRenderer.on('auto-switch-local', (_, source) => cb(source)),
  // Auto-launch
  getAutoLaunch: () => ipcRenderer.invoke('get-auto-launch'),
  setAutoLaunch: (enabled) => ipcRenderer.send('set-auto-launch', enabled),
  // Volume
  minibarVolumeScroll: (delta) => ipcRenderer.send('minibar-volume-scroll', delta),
  setVolumePreset: (vol) => ipcRenderer.send('set-volume-preset', vol),
  // History
  getHistory: () => ipcRenderer.invoke('get-history'),
  // Discord
  discordIsEnabled: () => ipcRenderer.invoke('discord-is-enabled'),
  discordEnable: () => ipcRenderer.send('discord-enable'),
  discordDisable: () => ipcRenderer.send('discord-disable'),
  // Spotify
  spotifyLogin: () => ipcRenderer.invoke('spotify-login'),
  spotifyLogout: () => ipcRenderer.invoke('spotify-logout'),
  spotifyIsLoggedIn: () => ipcRenderer.invoke('spotify-is-logged-in'),
  spotifyGetMe: () => ipcRenderer.invoke('spotify-get-me'),
  spotifyGetPlaylists: () => ipcRenderer.invoke('spotify-get-playlists'),
  spotifyGetPlaylistTracks: (id) => ipcRenderer.invoke('spotify-get-playlist-tracks', id),
  spotifyGetLiked: () => ipcRenderer.invoke('spotify-get-liked'),
  spotifySearch: (q) => ipcRenderer.invoke('spotify-search', q),
  spotifyGetPlayback: () => ipcRenderer.invoke('spotify-get-playback'),
  spotifyPlay: (ctx, track) => ipcRenderer.invoke('spotify-play', ctx, track),
  spotifyPause: () => ipcRenderer.invoke('spotify-pause'),
  spotifyNext: () => ipcRenderer.invoke('spotify-next'),
  spotifyPrevious: () => ipcRenderer.invoke('spotify-previous'),
  spotifySetVolume: (v) => ipcRenderer.invoke('spotify-set-volume', v),
  spotifyGetClientId: () => ipcRenderer.invoke('spotify-get-client-id'),
  spotifySetClientId: (id) => ipcRenderer.send('spotify-set-client-id', id),
  // Local files
  pickMusicFolder: () => ipcRenderer.invoke('pick-music-folder'),
  scanMusicFolder: (folder) => ipcRenderer.invoke('scan-music-folder', folder),
  getTrackArt: (path) => ipcRenderer.invoke('get-track-art', path),
  getMusicFolder: () => ipcRenderer.invoke('get-music-folder'),
  searchLocalFiles: (query) => ipcRenderer.invoke('search-local-files', query),
  getLocalAlbums: () => ipcRenderer.invoke('get-local-albums'),
  // Changelog
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  getLastSeenVersion: () => ipcRenderer.invoke('get-last-seen-version'),
  markChangelogSeen: (v) => ipcRenderer.send('mark-changelog-seen', v),
});

contextBridge.exposeInMainWorld('windowControls', {
  minimize: () => ipcRenderer.send('window-minimize'),
  close: () => ipcRenderer.send('window-close'),
  toggleLocket: () => ipcRenderer.send('toggle-locket'),
  toggleMinibar: () => ipcRenderer.send('toggle-minibar'),
  closeMinibar: () => ipcRenderer.send('close-minibar'),
  openMain: () => ipcRenderer.send('open-main'),
  launchSonos: () => ipcRenderer.send('launch-sonos'),
  quit: () => ipcRenderer.send('app-quit'),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  sendFeedback: (type, title, desc) => ipcRenderer.invoke('send-feedback', type, title, desc),
  setWidgetPosition: (target, pos) => ipcRenderer.send('set-widget-position', target, pos),
  ensureMinibar: () => ipcRenderer.invoke('ensure-minibar'),
  ensureLocket: () => ipcRenderer.invoke('ensure-locket'),
  isMinibarOpen: () => ipcRenderer.invoke('is-minibar-open'),
  isLocketOpen: () => ipcRenderer.invoke('is-locket-open'),
  onWidgetClosed: (cb) => ipcRenderer.on('widget-closed', (_, target) => cb(target)),
});
